version: '3'

services:
    app1:
        build:
            context: ./app1
            dockerfile: DockerFile
        deploy:
            replicas: 4
        ports:
            - "8000-8003:8000"
        networks:
            - fastapi-network
            
    app2:
        build:
            context: ./app2
            dockerfile: DockerFile
        deploy:
            replicas: 4
        ports:
            - "8100-8103:8100"
        networks:
            - fastapi-network
    
networks:
    fastapi-network:
        external: true